<a href="https://colab.research.google.com/github/DipankarJDutta/DipankarJDutta-Biomarker-discovery-from-B-T-cells-in-FASD-GDM-with-LSTM/blob/Peering-inside-the-Black-Box/LSTM_B-T-Median_Pairplots%20with%20Pairgrid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Fixing random seed to 007 for reproducibility
from numpy.random import seed
seed(7)
from tensorflow import set_random_seed
set_random_seed(7)

In [0]:
# Importing essentials
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [0]:
# Load data
dataset = pd.read_csv('B-T-median_+col-names_+learner-type.csv')

In [11]:
# Display top of data
dataset.head()

   Tnfaip3  Chchd7   Gnas   Pld4  ...    Wac  Tvp23b  Usp15       Learner
0    0.361   0.723  0.802  1.000  ...  0.956   0.379  0.833  Good-learner
1    0.692   0.676  0.686  1.000  ...  0.000   0.000  0.000  Good-learner
2    1.000   1.000  0.711  0.805  ...  0.000   0.000  0.000  Bad -learner
3    0.458   0.610  1.000  1.000  ...  0.868   1.000  0.914  Bad -learner
4    0.294   0.723  1.000  0.991  ...  0.831   1.000  0.719  Good-learner

[5 rows x 30 columns]

In [12]:
# Describe the data; 56 samples, range of 0 to 1 (not z-scored)
dataset.describe()

         Tnfaip3     Chchd7       Gnas  ...        Wac     Tvp23b      Usp15
count  56.000000  56.000000  56.000000  ...  56.000000  56.000000  56.000000
mean    0.745054   0.662339   0.646339  ...   0.735750   0.744232   0.740643
std     0.331375   0.251074   0.348948  ...   0.327935   0.375065   0.327794
min     0.000000   0.000000   0.000000  ...   0.000000   0.000000   0.000000
25%     0.511250   0.543750   0.370500  ...   0.716250   0.680500   0.747750
50%     1.000000   0.713500   0.698500  ...   0.833000   1.000000   0.869000
75%     1.000000   0.824000   1.000000  ...   1.000000   1.000000   0.941750
max     1.000000   1.000000   1.000000  ...   1.000000   1.000000   1.000000

[8 rows x 29 columns]

In [13]:
# Set Seaborn Style
sns.set(style = 'ticks', font= 'sans-serif', font_scale=1.25)

# Plot Pairplot
sns.pairplot(dataset, corner=True, kind="reg", hue='Learner')

#Save figure as svg
plt.savefig ('pairplot_B-T_median_diag-hist.svg', format = 'svg')

TypeError: ignored